// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbcvbdlrqrxfpttgpvtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiY3ZiZGxycXJ4ZnB0dGdwdnRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjA2MTgsImV4cCI6MjA2NzYzNjYxOH0.UWWgQ5JfStAogMiCwHa6M7bX322GPB-Kvb_12oMF5Fw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});